services:
  ffc-ice-crm:
    build:
      context: .
      target: production
    image: ffc-ice-crm
    container_name: ffc-ice-crm
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-ice-crm-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
