environment: production
environmentCode:
name: ffc-ice-crm
namespace: ffc-ice
workstream: ffc-ice
image: ffc-ice-crm 

labels:
  component: service

appInsights:
  connectionString:

containerConfigMap:
  name: ffc-ice-crm-config-map

containerSecret:
  name: ffc-ice-crm-container-secret
  type: Opaque

deployment: {}

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3000
  serviceBusConnectionString:  
  serviceBusHost: SNDFFCINFSB1001.servicebus.windows.net
  serviceBusUsername: 
  serviceBusPassword: 
  caseDetailsQueue: ffc-rpi-bao-casedetails
  crmApiHost:
  crmApiUrl:
  crmTenantID:
  crmClientID:
  crmClientSecret:

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 20
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 5

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID