{{- include "ffc-helm-library.container-secret" (list . "ffc-ice-crm.container-secret") -}}
{{- define "ffc-ice-crm.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
  {{- if .Values.container.serviceBusConnectionString }}
  SERVICE_BUS_CONNECTION_STRING: {{ quote .Values.container.serviceBusConnectionString }}
  {{- end }}
  {{- if .Values.container.serviceBusUsername }}
  SERVICE_BUS_USERNAME: {{ quote .Values.container.serviceBusUsername }}
  {{- end }}
  {{- if .Values.container.serviceBusPassword }}
  SERVICE_BUS_PASSWORD: {{ quote .Values.container.serviceBusPassword }}
  {{- end }}
  {{- if .Values.container.crmTenantID }}
  CRM_TENANT_ID: {{ quote .Values.container.crmTenantID }}
  {{- end }}
  {{- if .Values.container.crmClientID }}
  CRM_CLIENT_ID: {{ quote .Values.container.crmClientID }}
  {{- end }}
  {{- if .Values.container.crmClientSecret }}
  CRM_CLIENT_SECRET: {{ quote .Values.container.crmClientSecret }}
  {{- end }}
  {{- if .Values.container.rpaDocumentTypesEs }}
  RPA_DOCUMENT_TYPES_ES: {{ quote .Values.container.rpaDocumentTypesEs }}
  {{- end }}
{{- end -}}
